"use client";

import { useState } from "react";
import "./styles.css";

type Screen = "home"|"sip"|"sipPending"|"sipSuccess"|"sipFailed"|"portfolio"|"portfolioFund"|"restart"|"paymentFailed"|"withdraw"|"withdrawConfirm"|"withdrawOtp"|"withdrawPending"|"withdrawSuccess"|"withdrawFailed"|"withdrawReason";

const funds = [
  { name: "Edelweiss Gold and Silver ETF FoF", type: "Gold + Silver", value: "₹14,662.50", gain: "+₹1,183.93", pct: "8.07%" },
  { name: "Axis Gold Fund", type: "Gold", value: "₹33,097.50", gain: "+₹1,576.07", pct: "4.76%" },
  { name: "Axis Silver Fund", type: "Silver", value: "₹8,760.00", gain: "+₹765.00", pct: "13.04%" },
];
const money=(n:number)=>n.toLocaleString("en-IN");

export default function Prototype3(){
  const [screen,setScreen]=useState<Screen>("home");
  const [dark,setDark]=useState(false);
  const [sipAmount,setSipAmount]=useState(100);
  const [frequency,setFrequency]=useState("Daily");
  const [selectedFund,setSelectedFund]=useState(0);
  const [withdrawAmount,setWithdrawAmount]=useState(19500);
  const [otp,setOtp]=useState("");
  const selected=funds[selectedFund];
  const withdrawMax=selectedFund===0?39000:8760;
  const sipLabel=frequency==="Monthly"?\`₹${money(sipAmount)}/month\`:\`₹${money(sipAmount)}/day\`;
  const go=(s:Screen)=>setScreen(s);
  const header=(title:string,back=true)=><header className="p3-header">{back?<button className="p3-icon" onClick={()=>go("home")}>‹</button>:<span className="p3-brand">DMI</span>}<h1>{title}</h1><button className="p3-icon" onClick={()=>setDark(v=>!v)}>{dark?"☀":"☾"}</button></header>;

  const FundCard=({i}:{i:number})=><button className={\`p3-fund ${selectedFund===i?"selected":""}\`} onClick={()=>setSelectedFund(i)}><span className="p3-fund-icon">{i===0?"S":i===1?"G":"Ag"}</span><span><b>{funds[i].name}</b><small>{funds[i].type}</small></span><span className="p3-radio">{selectedFund===i?"✓":""}</span></button>;

  const orderStatus=(success:boolean,failed=false)=><div className="p3-page p3-scroll">{header(failed?"Payment failed":success?"₹10,000":"₹100/day SIP")}<section className={\`p3-hero-status ${failed?"error":success?"success":""}\`}><div className="p3-status-mark">{failed?"!":success?"✓":"…"}</div><h2>{failed?"Payment failed":success?"Your investment was successful":"Your SIP journey with DMI Finance has begun!"}</h2>{failed&&<p>Please try again.</p>}</section><section className="p3-card"><h3>Order status</h3>{["SIP creation","Payment initiation","Order approval by mutual fund company","Fulfilment of order"].map((x,i)=><div className="p3-timeline" key={x}><span className={failed&&i>0?"dot error":"dot"}>{failed&&i===1?"!":success||i===0?"✓":""}</span><div><b>{x}</b><small>{i===2?"8 Sep 2026 • 11:23 PM":"7 Sep 2026 • 2:34 PM"}</small></div></div>)}</section><section className="p3-card"><h3>Order details</h3>{[["ICICI Prudential Gold ETF FoF","₹80/day"],["Edelweiss Gold and Silver ETF FoF","₹100/day"],["ICICI Prudential Silver ETF FoF","₹20/day"],["Overall amount","₹100"],["From Account","AXIS Bank • 21756"],["Product","Sona-Chandi"],["Transaction ID","12334238947"]].map(x=><div className="p3-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</section>{failed?<div className="p3-actions"><button onClick={()=>go("sip")}>Retry</button><button className="secondary" onClick={()=>go("home")}>Try Other Method</button></div>:<button className="p3-primary bottom" onClick={()=>go("home")}>Done</button>}</div>;

  let app:React.ReactNode=null;
  if(screen==="home") app=<div className="p3-page p3-scroll">{header("Investment home",false)}<section className="p3-welcome"><h2>Start building<br/><strong>wealth</strong><br/>with DMI Finance!</h2></section><section className="p3-section"><div className="p3-section-title"><h3>Start investing in</h3><b>Sona-Chandi basket</b></div><p>Invest in Gold & Silver without the jewellery making charges</p><button className="p3-primary" onClick={()=>go("sip")}>Invest Now</button></section><section className="p3-section"><h3>Explore investments</h3><div className="p3-product"><b>Only Gold</b><span>Invest in Gold ETFs with market linked returns</span></div><div className="p3-product"><b>Only Silver</b><span>Invest in Silver with exposure to industrial growth</span></div><div className="p3-product"><b>Quick withdraw</b><span>Grow money faster than bank account. Withdraw in 30 seconds</span></div></section><section className="p3-section calculator"><h3>How much your money would’ve grown</h3><p>If you had invested</p><div className="p3-amount-line"><button>−</button><b>₹100</b><button>+</button></div><div className="p3-pills"><span>₹100</span><span>₹3,000</span></div><p>Over the past</p><div className="p3-pills"><span>1Y</span><span className="active">3Y</span><span>5Y</span><span>30Y</span></div><strong className="p3-growth">₹2,78,194</strong><small>Your investment would’ve become</small></section><button className="p3-secondary" onClick={()=>go("portfolio")}>View investment dashboard</button></div>;

  if(screen==="sip") app=<div className="p3-page p3-scroll">{header("Investing in Sona-Chandi")}<div className="p3-tabs"><button className="active">Setup SIP</button><button>One-time</button></div><section className="p3-sip"><div className="p3-fund-tabs"><span className="active">Gold+Silver</span><span>Gold</span><span>Silver</span></div><div className="p3-amount-line"><button onClick={()=>setSipAmount(Math.max(100,sipAmount-100))}>−</button><input value={sipAmount.toLocaleString("en-IN")} onChange={e=>setSipAmount(Number(e.target.value.replace(/\D/g,""))||0)}/><button onClick={()=>setSipAmount(sipAmount+100)}>+</button></div><div className="p3-pills"><button>₹100</button><button>₹3,000</button><button>₹10,000</button></div><select value={frequency} onChange={e=>setFrequency(e.target.value)}><option>Daily</option><option>Monthly</option></select></section><section className="p3-card"><div className="p3-payment"><span>First payment</span><b>Today</b><span>Next payment on</span><b>{frequency==="Monthly"?"29th Aug":"30th Jul"}</b></div><p>Your SIP (automatic investments) will be active until canceled. You can modify, pause, or cancel anytime.</p></section><section className="p3-card"><h3>Min</h3><FundCard i={0}/><FundCard i={1}/><FundCard i={2}/></section><div className="p3-investing">Investing in: <b>{sipLabel}</b></div><p className="p3-terms">By proceeding you agree to DMI Finance’s Terms & Conditions</p><button className="p3-primary bottom" onClick={()=>go("sipPending")}>Continue</button></div>;

  if(screen==="sipPending") app=orderStatus(false);
  if(screen==="sipSuccess") app=orderStatus(true);
  if(screen==="sipFailed") app=orderStatus(false,true);

  if(screen==="portfolio") app=<div className="p3-page p3-scroll">{header("Investment home",false)}<section className="p3-value"><span>Current value</span><strong>₹47,760</strong><small>As of 09:30 PM, 7 Sep, 2026</small><div className="p3-stat-grid"><div><span>Total invested</span><b>₹45,000</b></div><div><span>Total Returns</span><b>+₹2,760</b></div><div><span>Return %</span><b>+5.77%</b></div></div><div className="p3-actions"><button onClick={()=>go("sip")}>Invest More</button><button onClick={()=>go("withdraw")}>Withdraw</button></div></section><section className="p3-section"><h3>Invested in</h3><div className="p3-basket" onClick={()=>go("portfolioFund")}><b>Sona-Chandi basket</b><span>100%</span><strong>₹47,760.00</strong><small>+₹2,760.00 (5.77%)</small></div></section><section className="p3-section"><h3>Investment breakdown</h3><div className="p3-break"><span>Sona</span><b>87.7%</b><strong>₹41,895.00</strong><small>+₹1,995.00 (4.76%)</small></div><div className="p3-break"><span>Chandi</span><b>12.3%</b><strong>₹5,865.00</strong><small>+₹765.00 (13.04%)</small></div></section><section className="p3-section"><h3>Recent Orders</h3><div className="p3-order"><b>Axis Gold Fund</b><span>Withdraw • 03:32 PM • 18 Aug 2026</span><strong>₹500.00</strong><em>In Progress</em></div></section></div>;

  if(screen==="portfolioFund") app=<div className="p3-page p3-scroll">{header("Sona-Chandi")}<section className="p3-value"><span>Current value</span><strong>₹47,760.00</strong><small>As of 09:30 PM, 7 Sep, 2026</small><div className="p3-stat-grid"><div><span>Total invested</span><b>₹45,000</b></div><div><span>Total Returns</span><b>+₹2,760</b></div><div><span>Return %</span><b>+5.77%</b></div></div></section><section className="p3-section"><div className="p3-sip-active"><b>Daily SIP active at ₹100/-</b><span>Axis Bank • 78935</span><button>Manage</button><small>Next SIP on 8 Sep 2026</small></div></section><section className="p3-section"><h3>Your money is invested in</h3>{funds.slice(0,2).map(f=><div className="p3-basket" key={f.name}><b>{f.name}</b><strong>{f.value}</strong><small>{f.gain} ({f.pct})</small></div>)}</section><section className="p3-section"><h3>Investment breakdown</h3><div className="p3-break"><span>Sona</span><b>87.7%</b><strong>₹41,895.00</strong></div><div className="p3-break"><span>Chandi</span><b>12.3%</b><strong>₹5,865.00</strong></div></section></div>;

  if(screen==="restart"||screen==="paymentFailed") app=<div className="p3-page p3-scroll">{header("Investment home",false)}<section className="p3-value"><span>Current value</span><strong>₹0.00</strong><small>As of 09:30 PM, 7 Sep, 2026</small></section><section className="p3-alert"><b>{screen==="restart"?"Restart your SIP of ₹100 daily":"Payment failed for SIP of ₹100 daily"}</b><button onClick={()=>go("sip")}>{screen==="restart"?"Resume":"Retry"}</button></section><section className="p3-section"><h3>{screen==="restart"?"Previously invested in":"Invested in"}</h3><div className="p3-product"><b>Sona-Chandi basket</b><span>Invest in Gold & Silver without the jewellery making charges</span><button onClick={()=>go("sip")}>Re-invest</button></div><div className="p3-product"><b>Only Gold</b><span>Keep growing your money with gold. No extra charges</span></div><div className="p3-product"><b>Quick withdraw</b><span>Grow money faster than bank account. Withdraw in 30 seconds</span></div></section></div>;

  if(screen==="withdraw") app=<div className="p3-page">{header("Withdraw")}<section className="p3-withdraw-fund"><span className="p3-fund-icon">S</span><div><b>{selected.name}</b><small>Available for withdrawal</small></div><strong>₹{money(withdrawMax)}</strong></section><section className="p3-withdraw"><span>Total units</span><b>522.1235</b><h3>I want to withdraw</h3><div className="p3-amount-line"><button onClick={()=>setWithdrawAmount(Math.max(100,withdrawAmount-100))}>−</button><input value={withdrawAmount.toLocaleString("en-IN")} onChange={e=>setWithdrawAmount(Math.min(withdrawMax,Number(e.target.value.replace(/\D/g,""))||0))}/><button onClick={()=>setWithdrawAmount(Math.min(withdrawMax,withdrawAmount+100))}>+</button></div><div className="p3-pills"><button onClick={()=>setWithdrawAmount(Math.round(withdrawMax*.5))}>₹{money(Math.round(withdrawMax*.5))} (50%)</button><button onClick={()=>setWithdrawAmount(Math.round(withdrawMax*.75))}>₹{money(Math.round(withdrawMax*.75))} (75%)</button><button onClick={()=>setWithdrawAmount(withdrawMax)}>₹{money(withdrawMax)} (100%)</button></div><input className="p3-range" type="range" min="100" max={withdrawMax} step="100" value={withdrawAmount} onChange={e=>setWithdrawAmount(Number(e.target.value))}/><div className="p3-range-label"><span>₹100</span><span>₹{money(withdrawMax)}</span></div></section><section className="p3-card"><h3>Tax calculation & exit fees</h3><div className="p3-row"><span>Transferring to</span><b>AXIS Bank • 21756</b></div><p>By proceeding you agree to DMI Finance’s Terms & Conditions</p></section><button className="p3-primary bottom" onClick={()=>go("withdrawConfirm")}>Withdraw ₹{money(withdrawAmount)}</button></div>;

  if(screen==="withdrawConfirm") app=<Modal title="Confirm withdrawal amount" text="You are about to withdraw your investment amount" value={\`₹${money(withdrawAmount)}\`} confirm="Confirm" onConfirm={()=>go("withdrawOtp")} onClose={()=>go("withdraw")}/>;
  if(screen==="withdrawOtp") app=<Modal title={<>Confirm withdrawal amount with an<br/>OTP verification</>} text="You will receive an OTP on your registered phone **3210 & email ab***dal@gmail.com" value="" confirm="Confirm" otp otpValue={otp} setOtp={setOtp} onConfirm={()=>go("withdrawPending")} onClose={()=>go("withdraw")}/>;
  if(screen==="withdrawPending"||screen==="withdrawSuccess"||screen==="withdrawFailed") app=<div className="p3-page p3-scroll">{header("₹10,000")}<section className="p3-hero-status success"><div className="p3-status-mark">{screen==="withdrawFailed"?"!":"✓"}</div><h2>{screen==="withdrawPending"?"Withdrawal request submitted":screen==="withdrawSuccess"?"Withdrawn successfully":"Withdrawal failed"}</h2></section><section className="p3-card"><h3>Order status</h3>{["Order placement","Order approval by mutual fund company","Amount credit to bank account"].map(x=><div className="p3-timeline" key={x}><span className="dot">✓</span><div><b>{x}</b><small>7 Sep 2026 • 2:34 PM</small></div></div>)}</section><section className="p3-card"><h3>Order details</h3><div className="p3-row"><span>Units Withdrawn</span><b>{screen==="withdrawSuccess"?"133.8778":"To be updated"}</b></div><div className="p3-row"><span>Product</span><b>Sona-Chandi</b></div><div className="p3-row"><span>Transaction ID</span><b>12334238947</b></div></section>{screen==="withdrawFailed"?<button className="p3-primary bottom" onClick={()=>go("withdrawReason")}>Retry withdrawal</button>:<button className="p3-primary bottom" onClick={()=>go("home")}>Done</button>}</div>;
  if(screen==="withdrawReason") app=<Reason/>;

  function Modal({title,text,value,confirm,otp,otpValue,setOtp,onConfirm,onClose}:{title:React.ReactNode;text:string;value:string;confirm:string;otp?:boolean;otpValue?:string;setOtp?:(v:string)=>void;onConfirm:()=>void;onClose:()=>void}){return <div className="p3-modal-wrap"><div className="p3-backdrop" onClick={onClose}/><div className="p3-modal"><button className="p3-close" onClick={onClose}>×</button><h2>{title}</h2><p>{text}</p>{value&&<strong className="p3-modal-value">{value}</strong>}{otp&&<><div className="p3-otp">{[0,1,2,3,4,5].map(i=><input key={i} maxLength={1} value={otpValue?.[i]||""} onChange={e=>setOtp?.((otpValue||"").slice(0,i)+e.target.value.replace(/\D/g,"").slice(0,1)+(otpValue||"").slice(i+1))}/>)}</div><small>00:09</small></>}<button className="p3-primary" disabled={!!otp&&(otpValue||"").length<6} onClick={onConfirm}>{confirm}</button></div></div>}
  function Reason(){return <div className="p3-modal-wrap"><div className="p3-backdrop"/><div className="p3-modal"><h2>Why your withdrawal may fail</h2><p>Your funds may have active pledge on them</p><p>The mutual fund company or exchange servers may be temporarily down</p><p>Your bank server’s may be having issues</p><button className="p3-primary" onClick={()=>go("home")}>Understood</button></div></div>}

  return <main className={\`p3-shell ${dark?"dark":""}\`}>{app}</main>;
}
